# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I8sFsjefNAmlH3PjsmmWZ9uQhgnAJHir
"""

inp = input()

fa = []

while int(inp) >= 0:
    fa.append(int(inp)%2)

    inp = int(inp)/2

    if(int(inp) == 1):
        fa.append(int(inp))
        break
    

fa.reverse()
print(*fa)